### Get all events
GET http://localhost:8080/events
Accept: application/json

### Create an event
POST http://localhost:8080/events
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYWlsIiwiZXhwIjoxNzE5NzIyNzM3LCJ1c2VySWQiOjF9.fH-eRPHaejb7tsssP1bxbcP1Op3AIIeh6ipc7Af-dW4

{
  "name": "Third Event",
  "description": "This is my event",
  "dateTime": "2024-01-01T15:30:00.000Z",
  "location": "My Location"
}

### Get one event
GET http://localhost:8080/events/2
Accept: application/json

### Update an event
PUT http://localhost:8080/events/2
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYWlsIiwiZXhwIjoxNzE5NzIyNzM3LCJ1c2VySWQiOjF9.fH-eRPHaejb7tsssP1bxbcP1Op3AIIeh6ipc7Af-dW4

{
  "name": "Event 2 UPDATED!!!!!",
  "description": "This is my event updated",
  "dateTime": "2024-01-01T15:30:00.000Z",
  "location": "My Location"
}

### Delete an event
DELETE http://localhost:8080/events/1
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYWlsIiwiZXhwIjoxNzE5NzIyNzM3LCJ1c2VySWQiOjF9.fH-eRPHaejb7tsssP1bxbcP1Op3AIIeh6ipc7Af-dW4
```