### Get all events
GET http://localhost:8080/events
Accept: application/json

### Create an event
POST http://localhost:8080/events
Content-Type: application/json
Accept: application/json

{
  "name": 150.45,
  "description": "This is my event",
  "dateTime": "2024-01-01T15:30:00.000Z",
  "location": "My Location"
}

### Get one event
GET http://localhost:8080/events/2
Accept: application/json

### Update an event
PUT http://localhost:8080/events/2
Content-Type: application/json
Accept: application/json

{
  "name": "Event 2",
  "description": "This is my event updated",
  "dateTime": "2024-01-01T15:30:00.000Z",
  "location": "My Location"
}

### Delete an event
DELETE http://localhost:8080/events/1
Accept: application/json
```